blog/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^(?P<article_id>\d+)/share/$', views.ArticleShareView.as_view(), name='article_share'),
    url(r'^(?P<article_id>\d+)/comment/$', views.ArticleCommentView.as_view(), name='article_comment'),
    url(r'^tag/(?P<tag_slug>(\S)+)$', views.ArticlesListbyTagView.as_view(), name='articles_list_by_tag'),
    url(r'^(?P<slug>(\S)+)$', views.ArticleView.as_view(), name='article_details'),
    url(r'^$', views.ArticlesListView.as_view(), name='articles_list'),
]

myblog/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls',
                           namespace='blog',
                           app_name='blog'
                           )),
    url(r'^tinymce/', include('tinymce.urls')),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.core.urlresolvers import reverse
from taggit.managers import TaggableManager
from tinymce.models import HTMLField


ARTICLE_STATUS = (
    ('draft', 'draft'),
    ('published', 'published'),
)


class Article(models.Model):
    title = models.CharField(max_length=50)
    slug = models.SlugField(max_length=50, unique_for_date='publish_date')
    author = models.ForeignKey(User, related_name='blog_article')
    article = HTMLField()
    publish_date = models.DateTimeField(default=timezone.now)
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)
    article_status = models.CharField(max_length=20, choices=ARTICLE_STATUS, default='draft')
    tags = TaggableManager()

    class Meta:
        ordering = ('-publish_date',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:article_details',
                       args=[self.slug])


class Comment(models.Model):
    article = models.ForeignKey(Article, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    comment = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return 'Komentarz {} do artykułu {}'.format(self.comment, self.article)

blog/forms.py
from django import forms


class EmailArticleForm(forms.Form):
    sender = forms.CharField(max_length=20,
                             widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Twoje Imię'}))
    email_sender = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control',
                                                                   'placeholder': 'Twój adres e-mail'}))
    email_receiver = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control',
                                                                     'placeholder': 'Adres e-mail Twojego Znajomego'}))
    message = forms.CharField(max_length=200,
                              required=False,
                              widget=forms.Textarea(attrs={'class': 'form-control',
                                                           'placeholder': 'Jeśli chcesz wpisz tutaj treść wiadomości'}))


class CommentArticleForm(forms.Form):
    name = forms.CharField(max_length=25, widget=forms.TextInput(attrs={'class': 'form-control',
                                                                        'placeholder': 'Twoje Imię'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control',
                                                            'placeholder': 'Twój adres e-mail'}))
    comment = forms.CharField(max_length=200,
                              widget=forms.Textarea(attrs={'class': 'form-control',
                                                           'placeholder': 'wpisz tutaj treść komentarza'}))

blog/views.py
from .models import Article, Comment
from django.shortcuts import render, get_object_or_404
from django.views import View
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from .forms import CommentArticleForm, EmailArticleForm
from .services import send_article
from taggit.models import Tag
from django.db.models import Count


class ArticlesListView(View):

    def get(self, request):
        articles_list = Article.objects.filter(article_status='published')
        paginator = Paginator(articles_list, 2)
        page = request.GET.get('page')
        try:
            articles = paginator.page(page)
        except PageNotAnInteger:
            articles = paginator.page(1)
        except EmptyPage:
            articles = paginator.page(paginator.num_pages)
        context = {'articles': articles}
        return render(request, 'blog/articles/list.html', context)


class ArticlesListbyTagView(View):

    def get(self, request, tag_slug):
        tag = get_object_or_404(Tag, slug=tag_slug)
        articles_list = Article.objects.filter(article_status='published', tags__in=[tag])
        paginator = Paginator(articles_list, 2)
        page = request.GET.get('page')
        try:
            articles = paginator.page(page)
        except PageNotAnInteger:
            articles = paginator.page(1)
        except EmptyPage:
            articles = paginator.page(paginator.num_pages)
        context = {'articles': articles, 'tag': tag}
        return render(request, 'blog/articles/list.html', context)


class ArticleView(View):

    def get(self, request, slug):
        article = get_object_or_404(Article, slug=slug)
        comments = article.comments.filter(active=True)
        article_tags_ids = article.tags.values_list('id', flat=True)
        similar_articles = Article.objects.filter(tags__in=article_tags_ids).exclude(id=article.id)
        similar_articles = similar_articles.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish_date')[:2]
        context = {'article': article,
                   'comments': comments,
                   'similar_articles': similar_articles}
        return render(request, 'blog/articles/details.html', context)


class ArticleCommentView(View):

    def get(self, request, article_id):
        article = get_object_or_404(Article, pk=article_id)
        comment_form = CommentArticleForm()
        context = {'article': article,
                   'comment_form': comment_form}
        return render(request, 'blog/articles/comment.html', context)

    def post(self, request, article_id):
        article = get_object_or_404(Article, pk=article_id)
        article_url = request.build_absolute_uri(article.get_absolute_url())
        comment_form = CommentArticleForm(request.POST)
        added = False
        if comment_form.is_valid():
            cleaned_data = comment_form.cleaned_data
            new_comment = Comment.objects.create(name=cleaned_data['name'],
                                                 email=cleaned_data['email'],
                                                 comment=cleaned_data['comment'],
                                                 article=article)
            added = True
        context = {'added': added, 'article_url': article_url}
        return render(request, 'blog/articles/comment.html', context)


class ArticleShareView(View):

    def get(self, request, article_id):
        article = get_object_or_404(Article, pk=article_id)
        form = EmailArticleForm()
        context = {'article': article, 'form': form}
        return render(request, 'blog/articles/share.html', context)

    def post(self, request, article_id):
        article = get_object_or_404(Article, pk=article_id)
        article_url = request.build_absolute_uri(article.get_absolute_url())
        form = EmailArticleForm(request.POST)
        sent = False
        if form.is_valid():
            sent = send_article(article, form, article_url)
        context = {'sent': sent, 'article_url': article_url}
        return render(request, 'blog/articles/share.html', context)

blog/templates/blog/articles/comment.html
{% extends "blog/base.html" %}
{% block title %}Dodaj nowy komentarz{% endblock %}
{% block content %}

{% if added %}
<div class="alert alert-success" role="alert">
    <h4 class="alert-heading">Sukces!</h4>
    <hr>
    <p>Komentarz został dodany</p>
</div>
<p>
    <a href="{{ article_url }}" class="btn btn-success">Wróć do artykułu</a>
</p>
{% else %}
<h2 class="jumbotron p-3 mb-2 bg-info text-white">Dodaj nowy komentarz</h2>
<div>
    <form action="." method="post">
        {% for field in comment_form %}
        <div class="form-group">
            {{field}}
        </div>
        {% endfor %}
        {% csrf_token %}
        <input type="submit" value="Dodaj komentarz" class="btn btn-info">
    </form>
</div>
{% endif %}
{% endblock %}

blog/templates/blog/articles/details.html
{% extends "blog/base.html" %}
{% block title %}{{ article.title }}{% endblock %}
{% block content %}

<h1 class="jumbotron p-3 mb-2 bg-info text-white">{{ article.title }}</h1>
<p class="text-secondary">
    Opublikowany {{ article.publish_date }} przez {{ article.author }}
</p>
<p class="text-muted"> Tagi:
    {% for tag in article.tags.all %}
    <a href="{% url 'blog:articles_list_by_tag' tag.slug %}" class="text-secondary">
        {{ tag.name }}
    </a>
    {% if not forloop.last %}, {% endif %}
    {% endfor %}
</p>
<p>
    {{ article.article|safe }}
</p>
<p>
    <a href="{% url 'blog:article_share' article.pk %}" class="btn btn-secondary">
        Udostępnij ten artykuł via e-mail
    </a>
</p>

{% if similar_articles %}
<h4>Podobne posty</h4>
<ul class="list-group">
{% for article in similar_articles %}
<li class="list-group-item list-group-item-action list-group-item-light">
    <a href="{{ article.get_absolute_url }}" class="text-secondary">{{ article.title }}</a>
</li>
{% endfor %}
</ul>
{% endif %}
<br>
{% with comments.count as total_comments %}
<h2 class="alert alert-success">
    komentarz{{ total_comments|pluralize:",e" }}: {{ total_comments }}
</h2>
<hr>
{% endwith %}
{% for comment in comments %}
<div class="comment">
    <p class="info">
        Komentarz dodany przez {{ comment.name }}
        {{ comment.created }}
    </p>
    {{ comment.comment|linebreaks }}
    <hr>
</div>
{% empty %}
<p>Nie ma jeszcze żadnych komentarzy.</p>
{% endfor %}

<p>
    <a href="{% url 'blog:article_comment' article.pk %}" class="btn btn-secondary">Dodaj komentarz</a>
</p>

{% endblock %}

blog/templates/blog/articles/latest_articles.html
<ul>
{% for article in latest_articles %}
  <li>
    <a href="{{ article.get_absolute_url }}" class="text-secondary">{{ article.title }}</a>
  </li>
{% endfor %}
</ul>

blog/templates/blog/articles/list.html
{% extends "blog/base.html" %}
{% block title %}Wspólny mianownik wywiady{% endblock %}
{% block content %}
<h1 class="jumbotron p-3 mb-2 bg-info text-white">Wspólny mianownik wywiady</h1>

{% if tag %}
<h5 class="alert alert-warning">Artykuły z tagiem "{{ tag.name }}"</h5>
{% endif %}

{% for article in articles %}
<h2>
    <a href="{{ article.get_absolute_url }}" class="text-info">
        {{ article.title }}
    </a>
</h2>
<p class="text-muted"> Tagi:
    {% for tag in article.tags.all %}
    <a href="{% url 'blog:articles_list_by_tag' tag.slug %}" class="text-secondary">
      {{ tag.name }}
    </a>
    {% if not forloop.last %}, {% endif %}
  {% endfor %}
</p>
<p class="text-secondary">
    Opublikowany {{ article.publish }} przez {{ article.author }}
</p>
<p>
    {{ article.article|truncatewords:50|linebreaks }}
    <a href="{{ article.get_absolute_url }}" class="text-info text-left font-italic">
        czytaj więcej
    </a>
    <br><br>
</p>
{% endfor %}

<nav>
    <span class="pagination justify-content-center"/>
        {% if articles.has_previous %}
            <li><a class="page-link" href="?page={{ articles.previous_page_number }}">Poprzednia</a></li>
        {% endif %}
        {% for number in articles.paginator.page_range %}
            {% if articles.number == number %}
                <li class="page-item active">
                    <span class="page-link">{{ number }}
                        <span class="sr-only">(current)</span>
                    </span>
                </li>
            {% else %}
                <li class="page-item"><a class="page-link" href="?page={{ number }}">{{ number }}</a></li>
            {% endif %}
        {% endfor %}
        {% if articles.has_next %}
            <li><a class="page-link" href="?page={{ articles.next_page_number }}">Następna</a></li>
        {% endif %}
        </ul>
</nav>

{% endblock %}

blog/templates/blog/articles/share.html
{% extends "blog/base.html" %}
{% block title %}Udostępnij post{% endblock %}
{% block content %}

{% if sent %}
<div class="alert alert-success" role="alert">
    <h4 class="alert-heading">Sukces!</h4>
    <hr>
    <p>Wiadomość e-mail została wysłana.</p>
</div>
{% else %}
<h3 class="jumbotron p-3 mb-2 bg-info text-white">Udostępnij "{{ article.title }}" przez e-mail</h3>
<div>
    <form action="." method="post">
        {% for field in form %}
        <div class="form-group has-errors text-danger small">
            {{field.errors}}
        </div>
        <div class="form-group has-errors text-danger small">
        </div>
        <div class="form-group">
            {{field}}
        </div>
        {% endfor %}
        {% csrf_token %}
        <input type="submit" value="Wyślij wiadomość e-mail" class="btn btn-info">
    </form>
</div>
{% endif %}
{% endblock %}

blog/templates/blog/base.html
{% load blog_tags %}
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css"
          integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-sm-8">
            {% block content %}
            {% endblock %}
        </div>
        <div class="col-sm-4 jumbotron border">
            <h4>Taki tam blog z tekstami ze wspólnego mianownika</h4>
            <p> Dotychczas opublikowałem {% total_articles %} artykułów. </p>
            <hr>
            <h5>Najnowsze posty</h5>
            {% show_latest_articles 3 %}
            <hr>
            <h5>Najczęściej komentowane posty</h5>
            {% get_most_commented_articles as most_commented_articles %}
            <ul>
                {% for article in most_commented_articles %}
                <li>
                    <a href="{{ article.get_absolute_url }}" class="text-secondary">{{ article.title }}</a>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>
</body>
</html>